name: Build
on:
  push:
    branches:
      # - main
      - feature/add-ci-mvp
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.14.0
        with:
          enable-cache: 'true'
      - name: Test
        run: |
          devbox run test
